"""Add file_encryption_root_key

Revision ID: 16885c3bd99d
Revises: 7cf2c0e8a2e3
Create Date: 2026-01-31 15:13:33.058053

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "16885c3bd99d"
down_revision: Union[str, None] = "7cf2c0e8a2e3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
