"""Add index to request_nonces.timestamp column

Revision ID: 2c525e893192
Revises: 63d866f824e9
Create Date: 2026-01-24 19:28:16.248995

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2c525e893192"
down_revision: Union[str, None] = "63d866f824e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add index to request_nonces.timestamp for efficient cleanup queries
    op.create_index(op.f("ix_request_nonces_timestamp"), "request_nonces", ["timestamp"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the index from request_nonces.timestamp
    op.drop_index(op.f("ix_request_nonces_timestamp"), table_name="request_nonces")
    # ### end Alembic commands ###
