"""Add RelocationTask model

Revision ID: 4cb41a7faab6
Revises: 6b398cde9d3e
Create Date: 2026-03-31 01:25:13.406811

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4cb41a7faab6"
down_revision: Union[str, None] = "6b398cde9d3e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()

    if "relocation_tasks" not in tables:
        op.create_table(
            "relocation_tasks",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("task_id", sa.String(), nullable=False),
            sa.Column("inventory_id", sa.Integer(), nullable=False),
            sa.Column("file_path", sa.String(), nullable=False),
            sa.Column("source_location_id", sa.Integer(), nullable=False),
            sa.Column("source_location_name", sa.String(), nullable=False),
            sa.Column("target_location_id", sa.Integer(), nullable=False),
            sa.Column("target_location_name", sa.String(), nullable=False),
            sa.Column("status", sa.Enum("PENDING", "RUNNING", "COMPLETED", "FAILED", name="relocationtaskstatus"), nullable=False),
            sa.Column("bytes_total", sa.Integer(), nullable=False),
            sa.Column("bytes_transferred", sa.Integer(), nullable=False),
            sa.Column("error_message", sa.Text(), nullable=True),
            sa.Column("new_file_path", sa.String(), nullable=True),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
            sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
            sa.ForeignKeyConstraint(["inventory_id"], ["file_inventory.id"], ),
            sa.ForeignKeyConstraint(["source_location_id"], ["cold_storage_locations.id"], ),
            sa.ForeignKeyConstraint(["target_location_id"], ["cold_storage_locations.id"], ),
            sa.PrimaryKeyConstraint("id")
        )
        op.create_index(op.f("ix_relocation_tasks_created_at"), "relocation_tasks", ["created_at"], unique=False)
        op.create_index(op.f("ix_relocation_tasks_id"), "relocation_tasks", ["id"], unique=False)
        op.create_index(op.f("ix_relocation_tasks_inventory_id"), "relocation_tasks", ["inventory_id"], unique=False)
        op.create_index(op.f("ix_relocation_tasks_status"), "relocation_tasks", ["status"], unique=False)
        op.create_index(op.f("ix_relocation_tasks_task_id"), "relocation_tasks", ["task_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_relocation_tasks_task_id"), table_name="relocation_tasks")
    op.drop_index(op.f("ix_relocation_tasks_status"), table_name="relocation_tasks")
    op.drop_index(op.f("ix_relocation_tasks_inventory_id"), table_name="relocation_tasks")
    op.drop_index(op.f("ix_relocation_tasks_id"), table_name="relocation_tasks")
    op.drop_index(op.f("ix_relocation_tasks_created_at"), table_name="relocation_tasks")
    op.drop_table("relocation_tasks")
    # ### end Alembic commands ###
