"""Add RelocationTask model

Revision ID: 4cb41a7faab6
Revises: 6b398cde9d3e
Create Date: 2026-03-31 01:25:13.406811

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "4cb41a7faab6"
down_revision: Union[str, None] = "6b398cde9d3e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
