"""Initial database schema

Revision ID: 5f96d3126e3a
Revises: 
Create Date: 2026-01-06 15:08:42.185992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f96d3126e3a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitored_paths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source_path', sa.String(), nullable=False),
    sa.Column('cold_storage_path', sa.String(), nullable=False),
    sa.Column('operation_type', sa.Enum('MOVE', 'COPY', 'SYMLINK', name='operationtype'), nullable=True),
    sa.Column('check_interval_seconds', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('prevent_indexing', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitored_paths_id'), 'monitored_paths', ['id'], unique=False)
    op.create_index(op.f('ix_monitored_paths_name'), 'monitored_paths', ['name'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('criteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path_id', sa.Integer(), nullable=False),
    sa.Column('criterion_type', sa.Enum('MTIME', 'ATIME', 'CTIME', 'SIZE', 'NAME', 'INAME', 'TYPE', 'PERM', 'USER', 'GROUP', name='criteriontype'), nullable=False),
    sa.Column('operator', sa.Enum('GT', 'LT', 'EQ', 'GTE', 'LTE', 'CONTAINS', 'REGEX', 'MATCHES', name='operator'), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['path_id'], ['monitored_paths.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_criteria_id'), 'criteria', ['id'], unique=False)
    op.create_table('file_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('storage_type', sa.Enum('HOT', 'COLD', name='storagetype'), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_mtime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('file_atime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('file_ctime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.Column('file_extension', sa.String(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'MOVED', 'DELETED', 'MISSING', name='filestatus'), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['path_id'], ['monitored_paths.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index('idx_inventory_extension', 'file_inventory', ['file_extension'], unique=False)
    op.create_index('idx_inventory_path_storage_status', 'file_inventory', ['path_id', 'storage_type', 'status'], unique=False)
    op.create_index('idx_inventory_storage_status_lastseen', 'file_inventory', ['storage_type', 'status', 'last_seen'], unique=False)
    op.create_index(op.f('ix_file_inventory_checksum'), 'file_inventory', ['checksum'], unique=False)
    op.create_index(op.f('ix_file_inventory_file_atime'), 'file_inventory', ['file_atime'], unique=False)
    op.create_index(op.f('ix_file_inventory_file_extension'), 'file_inventory', ['file_extension'], unique=False)
    op.create_index(op.f('ix_file_inventory_file_mtime'), 'file_inventory', ['file_mtime'], unique=False)
    op.create_index(op.f('ix_file_inventory_file_path'), 'file_inventory', ['file_path'], unique=False)
    op.create_index(op.f('ix_file_inventory_file_size'), 'file_inventory', ['file_size'], unique=False)
    op.create_index(op.f('ix_file_inventory_id'), 'file_inventory', ['id'], unique=False)
    op.create_index(op.f('ix_file_inventory_last_seen'), 'file_inventory', ['last_seen'], unique=False)
    op.create_index(op.f('ix_file_inventory_path_id'), 'file_inventory', ['path_id'], unique=False)
    op.create_index(op.f('ix_file_inventory_status'), 'file_inventory', ['status'], unique=False)
    op.create_index(op.f('ix_file_inventory_storage_type'), 'file_inventory', ['storage_type'], unique=False)
    op.create_table('file_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path_id', sa.Integer(), nullable=True),
    sa.Column('original_path', sa.String(), nullable=False),
    sa.Column('cold_storage_path', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('moved_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('operation_type', sa.Enum('MOVE', 'COPY', 'SYMLINK', name='operationtype'), nullable=False),
    sa.Column('criteria_matched', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['path_id'], ['monitored_paths.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_records_id'), 'file_records', ['id'], unique=False)
    op.create_index(op.f('ix_file_records_moved_at'), 'file_records', ['moved_at'], unique=False)
    op.create_table('pinned_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('pinned_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('pinned_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['path_id'], ['monitored_paths.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pinned_files_file_path'), 'pinned_files', ['file_path'], unique=False)
    op.create_index(op.f('ix_pinned_files_id'), 'pinned_files', ['id'], unique=False)
    op.create_table('tag_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('criterion_type', sa.Enum('EXTENSION', 'PATH_PATTERN', 'MIME_TYPE', 'SIZE', 'NAME_PATTERN', name='tagrulecriteriontype'), nullable=False),
    sa.Column('operator', sa.Enum('GT', 'LT', 'EQ', 'GTE', 'LTE', 'CONTAINS', 'REGEX', 'MATCHES', name='operator'), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_rules_id'), 'tag_rules', ['id'], unique=False)
    op.create_index(op.f('ix_tag_rules_tag_id'), 'tag_rules', ['tag_id'], unique=False)
    op.create_table('file_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('tagged_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('tagged_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file_inventory.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index('idx_file_tag_unique', 'file_tags', ['file_id', 'tag_id'], unique=True)
    op.create_index(op.f('ix_file_tags_file_id'), 'file_tags', ['file_id'], unique=False)
    op.create_index(op.f('ix_file_tags_id'), 'file_tags', ['id'], unique=False)
    op.create_index(op.f('ix_file_tags_tag_id'), 'file_tags', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_tags_tag_id'), table_name='file_tags')
    op.drop_index(op.f('ix_file_tags_id'), table_name='file_tags')
    op.drop_index(op.f('ix_file_tags_file_id'), table_name='file_tags')
    op.drop_index('idx_file_tag_unique', table_name='file_tags')
    op.drop_table('file_tags')
    op.drop_index(op.f('ix_tag_rules_tag_id'), table_name='tag_rules')
    op.drop_index(op.f('ix_tag_rules_id'), table_name='tag_rules')
    op.drop_table('tag_rules')
    op.drop_index(op.f('ix_pinned_files_id'), table_name='pinned_files')
    op.drop_index(op.f('ix_pinned_files_file_path'), table_name='pinned_files')
    op.drop_table('pinned_files')
    op.drop_index(op.f('ix_file_records_moved_at'), table_name='file_records')
    op.drop_index(op.f('ix_file_records_id'), table_name='file_records')
    op.drop_table('file_records')
    op.drop_index(op.f('ix_file_inventory_storage_type'), table_name='file_inventory')
    op.drop_index(op.f('ix_file_inventory_status'), table_name='file_inventory')
    op.drop_index(op.f('ix_file_inventory_path_id'), table_name='file_inventory')
    op.drop_index(op.f('ix_file_inventory_last_seen'), table_name='file_inventory')
    op.drop_index(op.f('ix_file_inventory_id'), table_name='file_inventory')
    op.drop_index(op.f('ix_file_inventory_file_size'), table_name='file_inventory')
    op.drop_index(op.f('ix_file_inventory_file_path'), table_name='file_inventory')
    op.drop_index(op.f('ix_file_inventory_file_mtime'), table_name='file_inventory')
    op.drop_index(op.f('ix_file_inventory_file_extension'), table_name='file_inventory')
    op.drop_index(op.f('ix_file_inventory_file_atime'), table_name='file_inventory')
    op.drop_index(op.f('ix_file_inventory_checksum'), table_name='file_inventory')
    op.drop_index('idx_inventory_storage_status_lastseen', table_name='file_inventory')
    op.drop_index('idx_inventory_path_storage_status', table_name='file_inventory')
    op.drop_index('idx_inventory_extension', table_name='file_inventory')
    op.drop_table('file_inventory')
    op.drop_index(op.f('ix_criteria_id'), table_name='criteria')
    op.drop_table('criteria')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_monitored_paths_name'), table_name='monitored_paths')
    op.drop_index(op.f('ix_monitored_paths_id'), table_name='monitored_paths')
    op.drop_table('monitored_paths')
    # ### end Alembic commands ###
