"""Add OIDC settings to InstanceMetadata

Revision ID: 63a028912d0f
Revises: 5311846495bd
Create Date: 2026-07-02 20:47:18.377935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63a028912d0f'
down_revision: Union[str, None] = '5311846495bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = set(inspector.get_table_names())
    if "instance_metadata" not in tables:
        return

    columns = {column["name"] for column in inspector.get_columns("instance_metadata")}

    with op.batch_alter_table("instance_metadata") as batch_op:
        if "oidc_enabled" not in columns:
            batch_op.add_column(sa.Column('oidc_enabled', sa.Boolean(), nullable=True))
        if "oidc_client_id" not in columns:
            batch_op.add_column(sa.Column('oidc_client_id', sa.String(), nullable=True))
        if "oidc_client_secret" not in columns:
            batch_op.add_column(sa.Column('oidc_client_secret', sa.String(), nullable=True))
        if "oidc_issuer" not in columns:
            batch_op.add_column(sa.Column('oidc_issuer', sa.String(), nullable=True))
        if "oidc_redirect_uri" not in columns:
            batch_op.add_column(sa.Column('oidc_redirect_uri', sa.String(), nullable=True))
        if "oidc_provider_name" not in columns:
            batch_op.add_column(sa.Column('oidc_provider_name', sa.String(), nullable=True))
        if "oidc_roles_claim" not in columns:
            batch_op.add_column(sa.Column('oidc_roles_claim', sa.String(), nullable=True))
        if "oidc_admin_group" not in columns:
            batch_op.add_column(sa.Column('oidc_admin_group', sa.String(), nullable=True))
        if "oidc_manager_group" not in columns:
            batch_op.add_column(sa.Column('oidc_manager_group', sa.String(), nullable=True))
        if "oidc_viewer_group" not in columns:
            batch_op.add_column(sa.Column('oidc_viewer_group', sa.String(), nullable=True))
        if "oidc_default_roles" not in columns:
            batch_op.add_column(sa.Column('oidc_default_roles', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = set(inspector.get_table_names())
    if "instance_metadata" not in tables:
        return

    columns = {column["name"] for column in inspector.get_columns("instance_metadata")}

    with op.batch_alter_table("instance_metadata") as batch_op:
        if "oidc_default_roles" in columns:
            batch_op.drop_column('oidc_default_roles')
        if "oidc_viewer_group" in columns:
            batch_op.drop_column('oidc_viewer_group')
        if "oidc_manager_group" in columns:
            batch_op.drop_column('oidc_manager_group')
        if "oidc_admin_group" in columns:
            batch_op.drop_column('oidc_admin_group')
        if "oidc_roles_claim" in columns:
            batch_op.drop_column('oidc_roles_claim')
        if "oidc_provider_name" in columns:
            batch_op.drop_column('oidc_provider_name')
        if "oidc_redirect_uri" in columns:
            batch_op.drop_column('oidc_redirect_uri')
        if "oidc_issuer" in columns:
            batch_op.drop_column('oidc_issuer')
        if "oidc_client_secret" in columns:
            batch_op.drop_column('oidc_client_secret')
        if "oidc_client_id" in columns:
            batch_op.drop_column('oidc_client_id')
        if "oidc_enabled" in columns:
            batch_op.drop_column('oidc_enabled')
    # ### end Alembic commands ###
