"""Update TrustStatus enum values to uppercase

Revision ID: 63d866f824e9
Revises: da9c511bdeb2
Create Date: 2026-01-24 17:05:45.206896

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "63d866f824e9"
down_revision: Union[str, None] = "da9c511bdeb2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Update existing 'trust_status' values in 'remote_connections' table to uppercase
    op.execute(
        "UPDATE remote_connections SET trust_status = UPPER(trust_status) WHERE trust_status IS NOT NULL"
    )

    # Recreate the enum type for 'trust_status' with uppercase values
    # For SQLite, this typically means altering the column type to VARCHAR with check constraints.
    # The autogenerated compare already handled the enum signature, so this alter_column is just to ensure type alignment.
    with op.batch_alter_table("remote_connections", schema=None) as batch_op:
        batch_op.alter_column(
            "trust_status",
            existing_type=sa.VARCHAR(),  # Assuming the underlying type in SQLite was VARCHAR
            type_=sa.Enum("PENDING", "TRUSTED", "REJECTED", name="truststatus"),
            existing_nullable=False,
            server_default=sa.text("'PENDING'"),
        )


def downgrade() -> None:
    # Revert 'trust_status' column type and data to lowercase
    # For SQLite, this typically means altering the column type back to VARCHAR.
    with op.batch_alter_table("remote_connections", schema=None) as batch_op:
        batch_op.alter_column(
            "trust_status",
            existing_type=sa.Enum("PENDING", "TRUSTED", "REJECTED", name="truststatus"),
            type_=sa.VARCHAR(),  # Revert to generic VARCHAR
            existing_nullable=False,
            server_default=sa.text("'pending'"),
        )

    op.execute(
        "UPDATE remote_connections SET trust_status = LOWER(trust_status) WHERE trust_status IS NOT NULL"
    )
