"""align_remaining_schemas

Revision ID: 71dcd4684615
Revises: be6a79404001
Create Date: 2026-06-03 15:26:43.407334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71dcd4684615'
down_revision: Union[str, None] = 'be6a79404001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _table_exists(table: str) -> bool:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    return table in inspector.get_table_names()


def _index_exists(table: str, index: str) -> bool:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    return any(idx["name"] == index for idx in inspector.get_indexes(table))


def upgrade() -> None:
    # Drop request_nonces
    if _table_exists('request_nonces'):
        if _index_exists('request_nonces', 'ix_request_nonces_timestamp'):
            op.drop_index('ix_request_nonces_timestamp', table_name='request_nonces')
        if _index_exists('request_nonces', 'ix_request_nonces_nonce'):
            op.drop_index('ix_request_nonces_nonce', table_name='request_nonces')
        if _index_exists('request_nonces', 'ix_request_nonces_id'):
            op.drop_index('ix_request_nonces_id', table_name='request_nonces')
        if _index_exists('request_nonces', 'ix_request_nonces_fingerprint'):
            op.drop_index('ix_request_nonces_fingerprint', table_name='request_nonces')
        op.drop_table('request_nonces')

    # Drop remote_transfer_jobs
    if _table_exists('remote_transfer_jobs'):
        if _index_exists('remote_transfer_jobs', 'ix_remote_transfer_jobs_status'):
            op.drop_index('ix_remote_transfer_jobs_status', table_name='remote_transfer_jobs')
        if _index_exists('remote_transfer_jobs', 'ix_remote_transfer_jobs_id'):
            op.drop_index('ix_remote_transfer_jobs_id', table_name='remote_transfer_jobs')
        op.drop_table('remote_transfer_jobs')

    # Drop remote_connection_path_permissions
    if _table_exists('remote_connection_path_permissions'):
        if _index_exists('remote_connection_path_permissions', 'ix_remote_connection_path_permissions_id'):
            op.drop_index('ix_remote_connection_path_permissions_id', table_name='remote_connection_path_permissions')
        op.drop_table('remote_connection_path_permissions')

    # Drop remote_audit_logs
    if _table_exists('remote_audit_logs'):
        if _index_exists('remote_audit_logs', 'ix_remote_audit_logs_timestamp'):
            op.drop_index('ix_remote_audit_logs_timestamp', table_name='remote_audit_logs')
        if _index_exists('remote_audit_logs', 'ix_remote_audit_logs_status'):
            op.drop_index('ix_remote_audit_logs_status', table_name='remote_audit_logs')
        if _index_exists('remote_audit_logs', 'ix_remote_audit_logs_id'):
            op.drop_index('ix_remote_audit_logs_id', table_name='remote_audit_logs')
        if _index_exists('remote_audit_logs', 'ix_remote_audit_logs_event_type'):
            op.drop_index('ix_remote_audit_logs_event_type', table_name='remote_audit_logs')
        if _index_exists('remote_audit_logs', 'ix_remote_audit_logs_connection_id_timestamp'):
            op.drop_index('ix_remote_audit_logs_connection_id_timestamp', table_name='remote_audit_logs')
        op.drop_table('remote_audit_logs')

    # Drop remote_connections
    if _table_exists('remote_connections'):
        if _index_exists('remote_connections', 'ix_remote_connections_remote_fingerprint'):
            op.drop_index('ix_remote_connections_remote_fingerprint', table_name='remote_connections')
        if _index_exists('remote_connections', 'ix_remote_connections_name'):
            op.drop_index('ix_remote_connections_name', table_name='remote_connections')
        if _index_exists('remote_connections', 'ix_remote_connections_id'):
            op.drop_index('ix_remote_connections_id', table_name='remote_connections')
        op.drop_table('remote_connections')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_nonces',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fingerprint', sa.VARCHAR(), nullable=False),
    sa.Column('nonce', sa.VARCHAR(), nullable=False),
    sa.Column('timestamp', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_nonces_timestamp'), 'request_nonces', ['timestamp'], unique=False)
    op.create_index(op.f('ix_request_nonces_nonce'), 'request_nonces', ['nonce'], unique=1)
    op.create_index(op.f('ix_request_nonces_id'), 'request_nonces', ['id'], unique=False)
    op.create_index(op.f('ix_request_nonces_fingerprint'), 'request_nonces', ['fingerprint'], unique=False)
    op.create_table('remote_transfer_jobs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('file_inventory_id', sa.INTEGER(), nullable=False),
    sa.Column('remote_connection_id', sa.INTEGER(), nullable=False),
    sa.Column('remote_monitored_path_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=11), nullable=True),
    sa.Column('progress', sa.INTEGER(), nullable=True),
    sa.Column('current_size', sa.INTEGER(), nullable=True),
    sa.Column('total_size', sa.INTEGER(), nullable=False),
    sa.Column('start_time', sa.DATETIME(), nullable=True),
    sa.Column('end_time', sa.DATETIME(), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('retry_count', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('source_path', sa.VARCHAR(), nullable=False),
    sa.Column('relative_path', sa.VARCHAR(), nullable=False),
    sa.Column('storage_type', sa.VARCHAR(length=4), nullable=False),
    sa.Column('checksum', sa.VARCHAR(), nullable=True),
    sa.Column('current_speed', sa.INTEGER(), nullable=True),
    sa.Column('eta', sa.INTEGER(), nullable=True),
    sa.Column('direction', sa.VARCHAR(length=4), server_default=sa.text("'PUSH'"), nullable=False),
    sa.Column('strategy', sa.VARCHAR(length=4), server_default=sa.text("'COPY'"), nullable=False),
    sa.Column('conflict_resolution', sa.VARCHAR(length=9), server_default=sa.text("'OVERWRITE'"), nullable=False),
    sa.ForeignKeyConstraint(['file_inventory_id'], ['file_inventory.id'], ),
    sa.ForeignKeyConstraint(['remote_connection_id'], ['remote_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remote_transfer_jobs_status'), 'remote_transfer_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_remote_transfer_jobs_id'), 'remote_transfer_jobs', ['id'], unique=False)
    op.create_table('remote_connection_path_permissions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('remote_connection_id', sa.INTEGER(), nullable=False),
    sa.Column('monitored_path_id', sa.INTEGER(), nullable=False),
    sa.Column('can_browse', sa.BOOLEAN(), server_default=sa.text("'1'"), nullable=False),
    sa.Column('can_pull', sa.BOOLEAN(), server_default=sa.text("'1'"), nullable=False),
    sa.ForeignKeyConstraint(['monitored_path_id'], ['monitored_paths.id'], ),
    sa.ForeignKeyConstraint(['remote_connection_id'], ['remote_connections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('remote_connection_id', 'monitored_path_id', name=op.f('uq_conn_path_perm'))
    )
    op.create_index(op.f('ix_remote_connection_path_permissions_id'), 'remote_connection_path_permissions', ['id'], unique=False)
    op.create_table('remote_audit_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('connection_id', sa.INTEGER(), nullable=True),
    sa.Column('connection_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('direction', sa.VARCHAR(length=10), nullable=True),
    sa.Column('file_path', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('file_size', sa.BIGINT(), nullable=True),
    sa.Column('checksum', sa.VARCHAR(length=64), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['remote_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remote_audit_logs_timestamp'), 'remote_audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_remote_audit_logs_status'), 'remote_audit_logs', ['status'], unique=False)
    op.create_index(op.f('ix_remote_audit_logs_id'), 'remote_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_remote_audit_logs_event_type'), 'remote_audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_remote_audit_logs_connection_id_timestamp'), 'remote_audit_logs', ['connection_id', 'timestamp'], unique=False)
    op.create_table('remote_connections',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('url', sa.VARCHAR(), nullable=False),
    sa.Column('remote_fingerprint', sa.VARCHAR(), nullable=True),
    sa.Column('remote_ed25519_public_key', sa.TEXT(), nullable=True),
    sa.Column('remote_x25519_public_key', sa.TEXT(), nullable=True),
    sa.Column('trust_status', sa.VARCHAR(length=8), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('transfer_mode', sa.VARCHAR(length=13), server_default=sa.text("'PUSH_ONLY'"), nullable=False),
    sa.Column('remote_transfer_mode', sa.VARCHAR(length=13), server_default=sa.text("'PUSH_ONLY'"), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('last_seen_at', sa.DATETIME(), nullable=True),
    sa.Column('is_reachable', sa.BOOLEAN(), server_default=sa.text("'1'"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remote_connections_remote_fingerprint'), 'remote_connections', ['remote_fingerprint'], unique=1)
    op.create_index(op.f('ix_remote_connections_name'), 'remote_connections', ['name'], unique=False)
    op.create_index(op.f('ix_remote_connections_id'), 'remote_connections', ['id'], unique=False)
    # ### end Alembic commands ###
