"""Add encryption support

Revision ID: 7cf2c0e8a2e3
Revises: 5c67e9e65fc0
Create Date: 2026-01-31 14:29:38.253350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '7cf2c0e8a2e3'
down_revision: Union[str, None] = '5c67e9e65fc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instance_key_history_fingerprint'), table_name='instance_key_history')
    op.drop_index(op.f('ix_instance_key_history_id'), table_name='instance_key_history')
    op.drop_index(op.f('ix_instance_key_history_key_version'), table_name='instance_key_history')
    op.drop_table('instance_key_history')
    op.drop_index(op.f('ix_monitored_paths_id'), table_name='monitored_paths')
    op.drop_index(op.f('ix_monitored_paths_name'), table_name='monitored_paths')
    op.drop_table('monitored_paths')
    op.drop_index(op.f('ix_remote_transfer_jobs_status'), table_name='remote_transfer_jobs')
    op.drop_table('remote_transfer_jobs')
    op.drop_index(op.f('ix_notifiers_id'), table_name='notifiers')
    op.drop_index(op.f('ix_notifiers_name'), table_name='notifiers')
    op.drop_table('notifiers')
    op.drop_index(op.f('ix_remote_connections_name'), table_name='remote_connections')
    op.drop_index(op.f('ix_remote_connections_remote_fingerprint'), table_name='remote_connections')
    op.drop_table('remote_connections')
    op.drop_index(op.f('ix_criteria_id'), table_name='criteria')
    op.drop_table('criteria')
    op.drop_index(op.f('idx_history_file_type'), table_name='file_transaction_history')
    op.drop_index(op.f('idx_history_time_range'), table_name='file_transaction_history')
    op.drop_index(op.f('ix_file_transaction_history_created_at'), table_name='file_transaction_history')
    op.drop_index(op.f('ix_file_transaction_history_file_id'), table_name='file_transaction_history')
    op.drop_index(op.f('ix_file_transaction_history_success'), table_name='file_transaction_history')
    op.drop_index(op.f('ix_file_transaction_history_transaction_type'), table_name='file_transaction_history')
    op.drop_table('file_transaction_history')
    op.drop_index(op.f('ix_tag_rules_id'), table_name='tag_rules')
    op.drop_index(op.f('ix_tag_rules_tag_id'), table_name='tag_rules')
    op.drop_table('tag_rules')
    op.drop_index(op.f('ix_file_records_cold_storage_location_id'), table_name='file_records')
    op.drop_index(op.f('ix_file_records_id'), table_name='file_records')
    op.drop_index(op.f('ix_file_records_moved_at'), table_name='file_records')
    op.drop_table('file_records')
    op.drop_index(op.f('ix_instance_metadata_id'), table_name='instance_metadata')
    op.drop_table('instance_metadata')
    op.drop_index(op.f('ix_pinned_files_file_path'), table_name='pinned_files')
    op.drop_index(op.f('ix_pinned_files_id'), table_name='pinned_files')
    op.drop_table('pinned_files')
    op.drop_index(op.f('ix_security_audit_log_event_type'), table_name='security_audit_log')
    op.drop_index(op.f('ix_security_audit_log_id'), table_name='security_audit_log')
    op.drop_index(op.f('ix_security_audit_log_timestamp'), table_name='security_audit_log')
    op.drop_table('security_audit_log')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_cold_storage_locations_id'), table_name='cold_storage_locations')
    op.drop_index(op.f('ix_cold_storage_locations_name'), table_name='cold_storage_locations')
    op.drop_table('cold_storage_locations')
    op.drop_index(op.f('ix_request_nonces_fingerprint'), table_name='request_nonces')
    op.drop_index(op.f('ix_request_nonces_id'), table_name='request_nonces')
    op.drop_index(op.f('ix_request_nonces_nonce'), table_name='request_nonces')
    op.drop_index(op.f('ix_request_nonces_timestamp'), table_name='request_nonces')
    op.drop_table('request_nonces')
    op.drop_index(op.f('ix_notification_dispatches_id'), table_name='notification_dispatches')
    op.drop_index(op.f('ix_notification_dispatches_notification_id'), table_name='notification_dispatches')
    op.drop_index(op.f('ix_notification_dispatches_notifier_id'), table_name='notification_dispatches')
    op.drop_index(op.f('ix_notification_dispatches_timestamp'), table_name='notification_dispatches')
    op.drop_table('notification_dispatches')
    op.drop_table('path_storage_location_association')
    op.drop_index(op.f('idx_file_tag_unique'), table_name='file_tags')
    op.drop_index(op.f('ix_file_tags_file_id'), table_name='file_tags')
    op.drop_index(op.f('ix_file_tags_id'), table_name='file_tags')
    op.drop_index(op.f('ix_file_tags_tag_id'), table_name='file_tags')
    op.drop_table('file_tags')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_level'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('idx_inventory_extension'), table_name='file_inventory')
    op.drop_index(op.f('idx_inventory_path_storage_status'), table_name='file_inventory')
    op.drop_index(op.f('idx_inventory_storage_status_lastseen'), table_name='file_inventory')
    op.drop_index(op.f('ix_file_inventory_checksum'), table_name='file_inventory')
    op.drop_index(op.f('ix_file_inventory_cold_storage_location_id'), table_name='file_inventory')
    op.drop_index(op.f('ix_file_inventory_file_atime'), table_name='file_inventory')
    op.drop_index(op.f('ix_file_inventory_file_extension'), table_name='file_inventory')
    op.drop_index(op.f('ix_file_inventory_file_mtime'), table_name='file_inventory')
    op.drop_index(op.f('ix_file_inventory_file_path'), table_name='file_inventory')
    op.drop_index(op.f('ix_file_inventory_file_size'), table_name='file_inventory')
    op.drop_index(op.f('ix_file_inventory_id'), table_name='file_inventory')
    op.drop_index(op.f('ix_file_inventory_last_seen'), table_name='file_inventory')
    op.drop_index(op.f('ix_file_inventory_path_id'), table_name='file_inventory')
    op.drop_index(op.f('ix_file_inventory_status'), table_name='file_inventory')
    op.drop_index(op.f('ix_file_inventory_storage_type'), table_name='file_inventory')
    op.drop_table('file_inventory')
    op.drop_index(op.f('ix_server_encryption_keys_fingerprint'), table_name='server_encryption_keys')
    op.drop_index(op.f('ix_server_encryption_keys_id'), table_name='server_encryption_keys')
    op.drop_table('server_encryption_keys')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_encryption_keys',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('key_value', sa.VARCHAR(), nullable=False),
    sa.Column('fingerprint', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_server_encryption_keys_id'), 'server_encryption_keys', ['id'], unique=False)
    op.create_index(op.f('ix_server_encryption_keys_fingerprint'), 'server_encryption_keys', ['fingerprint'], unique=1)
    op.create_table('file_inventory',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('path_id', sa.INTEGER(), nullable=False),
    sa.Column('cold_storage_location_id', sa.INTEGER(), nullable=True),
    sa.Column('file_path', sa.VARCHAR(), nullable=False),
    sa.Column('storage_type', sa.VARCHAR(length=4), nullable=False),
    sa.Column('file_size', sa.INTEGER(), nullable=False),
    sa.Column('file_mtime', sa.DATETIME(), nullable=False),
    sa.Column('file_atime', sa.DATETIME(), nullable=True),
    sa.Column('file_ctime', sa.DATETIME(), nullable=True),
    sa.Column('checksum', sa.VARCHAR(), nullable=True),
    sa.Column('file_extension', sa.VARCHAR(), nullable=True),
    sa.Column('mime_type', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=9), nullable=True),
    sa.Column('last_seen', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['cold_storage_location_id'], ['cold_storage_locations.id'], ),
    sa.ForeignKeyConstraint(['path_id'], ['monitored_paths.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_inventory_storage_type'), 'file_inventory', ['storage_type'], unique=False)
    op.create_index(op.f('ix_file_inventory_status'), 'file_inventory', ['status'], unique=False)
    op.create_index(op.f('ix_file_inventory_path_id'), 'file_inventory', ['path_id'], unique=False)
    op.create_index(op.f('ix_file_inventory_last_seen'), 'file_inventory', ['last_seen'], unique=False)
    op.create_index(op.f('ix_file_inventory_id'), 'file_inventory', ['id'], unique=False)
    op.create_index(op.f('ix_file_inventory_file_size'), 'file_inventory', ['file_size'], unique=False)
    op.create_index(op.f('ix_file_inventory_file_path'), 'file_inventory', ['file_path'], unique=False)
    op.create_index(op.f('ix_file_inventory_file_mtime'), 'file_inventory', ['file_mtime'], unique=False)
    op.create_index(op.f('ix_file_inventory_file_extension'), 'file_inventory', ['file_extension'], unique=False)
    op.create_index(op.f('ix_file_inventory_file_atime'), 'file_inventory', ['file_atime'], unique=False)
    op.create_index(op.f('ix_file_inventory_cold_storage_location_id'), 'file_inventory', ['cold_storage_location_id'], unique=False)
    op.create_index(op.f('ix_file_inventory_checksum'), 'file_inventory', ['checksum'], unique=False)
    op.create_index(op.f('idx_inventory_storage_status_lastseen'), 'file_inventory', ['storage_type', 'status', 'last_seen'], unique=False)
    op.create_index(op.f('idx_inventory_path_storage_status'), 'file_inventory', ['path_id', 'storage_type', 'status'], unique=False)
    op.create_index(op.f('idx_inventory_extension'), 'file_inventory', ['file_extension'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('color', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=1)
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('level', sa.VARCHAR(length=7), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_level'), 'notifications', ['level'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_table('file_tags',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('file_id', sa.INTEGER(), nullable=False),
    sa.Column('tag_id', sa.INTEGER(), nullable=False),
    sa.Column('tagged_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('tagged_by', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file_inventory.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_tags_tag_id'), 'file_tags', ['tag_id'], unique=False)
    op.create_index(op.f('ix_file_tags_id'), 'file_tags', ['id'], unique=False)
    op.create_index(op.f('ix_file_tags_file_id'), 'file_tags', ['file_id'], unique=False)
    op.create_index(op.f('idx_file_tag_unique'), 'file_tags', ['file_id', 'tag_id'], unique=1)
    op.create_table('path_storage_location_association',
    sa.Column('path_id', sa.INTEGER(), nullable=False),
    sa.Column('storage_location_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['path_id'], ['monitored_paths.id'], ),
    sa.ForeignKeyConstraint(['storage_location_id'], ['cold_storage_locations.id'], ),
    sa.PrimaryKeyConstraint('path_id', 'storage_location_id')
    )
    op.create_table('notification_dispatches',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('notification_id', sa.INTEGER(), nullable=False),
    sa.Column('notifier_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=7), nullable=False),
    sa.Column('details', sa.TEXT(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ),
    sa.ForeignKeyConstraint(['notifier_id'], ['notifiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_dispatches_timestamp'), 'notification_dispatches', ['timestamp'], unique=False)
    op.create_index(op.f('ix_notification_dispatches_notifier_id'), 'notification_dispatches', ['notifier_id'], unique=False)
    op.create_index(op.f('ix_notification_dispatches_notification_id'), 'notification_dispatches', ['notification_id'], unique=False)
    op.create_index(op.f('ix_notification_dispatches_id'), 'notification_dispatches', ['id'], unique=False)
    op.create_table('request_nonces',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fingerprint', sa.VARCHAR(), nullable=False),
    sa.Column('nonce', sa.VARCHAR(), nullable=False),
    sa.Column('timestamp', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_nonces_timestamp'), 'request_nonces', ['timestamp'], unique=False)
    op.create_index(op.f('ix_request_nonces_nonce'), 'request_nonces', ['nonce'], unique=1)
    op.create_index(op.f('ix_request_nonces_id'), 'request_nonces', ['id'], unique=False)
    op.create_index(op.f('ix_request_nonces_fingerprint'), 'request_nonces', ['fingerprint'], unique=False)
    op.create_table('cold_storage_locations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('path', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('caution_threshold_percent', sa.INTEGER(), server_default=sa.text("'20'"), nullable=False),
    sa.Column('critical_threshold_percent', sa.INTEGER(), server_default=sa.text("'10'"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_index(op.f('ix_cold_storage_locations_name'), 'cold_storage_locations', ['name'], unique=1)
    op.create_index(op.f('ix_cold_storage_locations_id'), 'cold_storage_locations', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('roles', sqlite.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=1)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('security_audit_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('event_type', sa.VARCHAR(), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('initiated_by', sa.VARCHAR(), nullable=True),
    sa.Column('event_metadata', sqlite.JSON(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_audit_log_timestamp'), 'security_audit_log', ['timestamp'], unique=False)
    op.create_index(op.f('ix_security_audit_log_id'), 'security_audit_log', ['id'], unique=False)
    op.create_index(op.f('ix_security_audit_log_event_type'), 'security_audit_log', ['event_type'], unique=False)
    op.create_table('pinned_files',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('path_id', sa.INTEGER(), nullable=True),
    sa.Column('file_path', sa.VARCHAR(), nullable=False),
    sa.Column('pinned_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('pinned_by', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['path_id'], ['monitored_paths.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pinned_files_id'), 'pinned_files', ['id'], unique=False)
    op.create_index(op.f('ix_pinned_files_file_path'), 'pinned_files', ['file_path'], unique=False)
    op.create_table('instance_metadata',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('instance_uuid', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('ed25519_public_key', sa.TEXT(), nullable=True),
    sa.Column('ed25519_private_key_encrypted', sa.TEXT(), nullable=True),
    sa.Column('x25519_public_key', sa.TEXT(), nullable=True),
    sa.Column('x25519_private_key_encrypted', sa.TEXT(), nullable=True),
    sa.Column('current_key_version', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False),
    sa.Column('instance_url', sa.VARCHAR(), nullable=True),
    sa.Column('instance_name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instance_uuid')
    )
    op.create_index(op.f('ix_instance_metadata_id'), 'instance_metadata', ['id'], unique=False)
    op.create_table('file_records',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('path_id', sa.INTEGER(), nullable=True),
    sa.Column('cold_storage_location_id', sa.INTEGER(), nullable=True),
    sa.Column('original_path', sa.VARCHAR(), nullable=False),
    sa.Column('cold_storage_path', sa.VARCHAR(), nullable=False),
    sa.Column('file_size', sa.INTEGER(), nullable=False),
    sa.Column('moved_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('operation_type', sa.VARCHAR(length=7), nullable=False),
    sa.Column('criteria_matched', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['cold_storage_location_id'], ['cold_storage_locations.id'], ),
    sa.ForeignKeyConstraint(['path_id'], ['monitored_paths.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_records_moved_at'), 'file_records', ['moved_at'], unique=False)
    op.create_index(op.f('ix_file_records_id'), 'file_records', ['id'], unique=False)
    op.create_index(op.f('ix_file_records_cold_storage_location_id'), 'file_records', ['cold_storage_location_id'], unique=False)
    op.create_table('tag_rules',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tag_id', sa.INTEGER(), nullable=False),
    sa.Column('criterion_type', sa.VARCHAR(length=12), nullable=False),
    sa.Column('operator', sa.VARCHAR(length=8), nullable=False),
    sa.Column('value', sa.VARCHAR(), nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), nullable=False),
    sa.Column('priority', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_rules_tag_id'), 'tag_rules', ['tag_id'], unique=False)
    op.create_index(op.f('ix_tag_rules_id'), 'tag_rules', ['id'], unique=False)
    op.create_table('file_transaction_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('file_id', sa.INTEGER(), nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=14), nullable=False),
    sa.Column('old_storage_type', sa.VARCHAR(length=4), nullable=True),
    sa.Column('new_storage_type', sa.VARCHAR(length=4), nullable=True),
    sa.Column('old_status', sa.VARCHAR(length=9), nullable=True),
    sa.Column('new_status', sa.VARCHAR(length=9), nullable=True),
    sa.Column('old_path', sa.VARCHAR(), nullable=True),
    sa.Column('new_path', sa.VARCHAR(), nullable=True),
    sa.Column('old_storage_location_id', sa.INTEGER(), nullable=True),
    sa.Column('new_storage_location_id', sa.INTEGER(), nullable=True),
    sa.Column('file_size', sa.INTEGER(), nullable=True),
    sa.Column('checksum_before', sa.VARCHAR(), nullable=True),
    sa.Column('checksum_after', sa.VARCHAR(), nullable=True),
    sa.Column('operation_metadata', sa.TEXT(), nullable=True),
    sa.Column('success', sa.BOOLEAN(), nullable=False),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('initiated_by', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file_inventory.id'], name=op.f('fk_file_transaction_history_file')),
    sa.ForeignKeyConstraint(['new_storage_location_id'], ['cold_storage_locations.id'], name=op.f('fk_file_transaction_history_new_storage_location')),
    sa.ForeignKeyConstraint(['old_storage_location_id'], ['cold_storage_locations.id'], name=op.f('fk_file_transaction_history_old_storage_location')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file_transaction_history'))
    )
    op.create_index(op.f('ix_file_transaction_history_transaction_type'), 'file_transaction_history', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_file_transaction_history_success'), 'file_transaction_history', ['success'], unique=False)
    op.create_index(op.f('ix_file_transaction_history_file_id'), 'file_transaction_history', ['file_id'], unique=False)
    op.create_index(op.f('ix_file_transaction_history_created_at'), 'file_transaction_history', ['created_at'], unique=False)
    op.create_index(op.f('idx_history_time_range'), 'file_transaction_history', ['created_at', 'success'], unique=False)
    op.create_index(op.f('idx_history_file_type'), 'file_transaction_history', ['file_id', 'transaction_type'], unique=False)
    op.create_table('criteria',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('path_id', sa.INTEGER(), nullable=False),
    sa.Column('criterion_type', sa.VARCHAR(length=5), nullable=False),
    sa.Column('operator', sa.VARCHAR(length=8), nullable=False),
    sa.Column('value', sa.VARCHAR(), nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['path_id'], ['monitored_paths.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_criteria_id'), 'criteria', ['id'], unique=False)
    op.create_table('remote_connections',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('url', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('remote_fingerprint', sa.VARCHAR(), nullable=True),
    sa.Column('remote_ed25519_public_key', sa.TEXT(), nullable=True),
    sa.Column('remote_x25519_public_key', sa.TEXT(), nullable=True),
    sa.Column('trust_status', sa.VARCHAR(length=8), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('transfer_mode', sa.VARCHAR(length=13), server_default=sa.text("'PUSH_ONLY'"), nullable=False),
    sa.Column('remote_transfer_mode', sa.VARCHAR(length=13), server_default=sa.text("'PUSH_ONLY'"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remote_connections_remote_fingerprint'), 'remote_connections', ['remote_fingerprint'], unique=1)
    op.create_index(op.f('ix_remote_connections_name'), 'remote_connections', ['name'], unique=False)
    op.create_table('notifiers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=15), nullable=False),
    sa.Column('address', sa.VARCHAR(), nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('smtp_host', sa.VARCHAR(), nullable=True),
    sa.Column('smtp_port', sa.INTEGER(), nullable=True),
    sa.Column('smtp_user', sa.VARCHAR(), nullable=True),
    sa.Column('smtp_sender', sa.VARCHAR(), nullable=True),
    sa.Column('smtp_use_tls', sa.BOOLEAN(), nullable=True),
    sa.Column('subscribed_events', sqlite.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('smtp_password', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifiers_name'), 'notifiers', ['name'], unique=False)
    op.create_index(op.f('ix_notifiers_id'), 'notifiers', ['id'], unique=False)
    op.create_table('remote_transfer_jobs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('file_inventory_id', sa.INTEGER(), nullable=False),
    sa.Column('remote_connection_id', sa.INTEGER(), nullable=False),
    sa.Column('remote_monitored_path_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('progress', sa.INTEGER(), nullable=True),
    sa.Column('current_size', sa.INTEGER(), nullable=True),
    sa.Column('total_size', sa.INTEGER(), nullable=False),
    sa.Column('start_time', sa.DATETIME(), nullable=True),
    sa.Column('end_time', sa.DATETIME(), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('retry_count', sa.INTEGER(), nullable=True),
    sa.Column('source_path', sa.VARCHAR(), nullable=False),
    sa.Column('relative_path', sa.VARCHAR(), nullable=False),
    sa.Column('storage_type', sa.VARCHAR(), nullable=False),
    sa.Column('checksum', sa.VARCHAR(), nullable=True),
    sa.Column('current_speed', sa.INTEGER(), nullable=True),
    sa.Column('eta', sa.INTEGER(), nullable=True),
    sa.Column('direction', sa.VARCHAR(length=4), server_default=sa.text("'PUSH'"), nullable=False),
    sa.ForeignKeyConstraint(['file_inventory_id'], ['file_inventory.id'], ),
    sa.ForeignKeyConstraint(['remote_connection_id'], ['remote_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remote_transfer_jobs_status'), 'remote_transfer_jobs', ['status'], unique=False)
    op.create_table('monitored_paths',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('source_path', sa.VARCHAR(), nullable=False),
    sa.Column('operation_type', sa.VARCHAR(length=7), nullable=True),
    sa.Column('check_interval_seconds', sa.INTEGER(), nullable=True),
    sa.Column('enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('prevent_indexing', sa.BOOLEAN(), nullable=False),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('last_scan_at', sa.DATETIME(), nullable=True),
    sa.Column('last_scan_status', sa.VARCHAR(length=7), nullable=True),
    sa.Column('last_scan_error_log', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitored_paths_name'), 'monitored_paths', ['name'], unique=False)
    op.create_index(op.f('ix_monitored_paths_id'), 'monitored_paths', ['id'], unique=False)
    op.create_table('instance_key_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('key_version', sa.INTEGER(), nullable=False),
    sa.Column('ed25519_public_key', sa.TEXT(), nullable=False),
    sa.Column('ed25519_private_key_encrypted', sa.TEXT(), nullable=False),
    sa.Column('x25519_public_key', sa.TEXT(), nullable=False),
    sa.Column('x25519_private_key_encrypted', sa.TEXT(), nullable=False),
    sa.Column('fingerprint', sa.VARCHAR(), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('retired_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instance_key_history_key_version'), 'instance_key_history', ['key_version'], unique=1)
    op.create_index(op.f('ix_instance_key_history_id'), 'instance_key_history', ['id'], unique=False)
    op.create_index(op.f('ix_instance_key_history_fingerprint'), 'instance_key_history', ['fingerprint'], unique=1)
    # ### end Alembic commands ###
