"""Unified initial database schema

Revision ID: a_unified_migration
Revises: 
Create Date: 2026-01-17 14:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a_unified_migration"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "monitored_paths",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("source_path", sa.String(), nullable=False),
        sa.Column(
            "operation_type",
            sa.Enum("MOVE", "COPY", "SYMLINK", name="operationtype"),
            nullable=True,
        ),
        sa.Column("check_interval_seconds", sa.Integer(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("prevent_indexing", sa.Boolean(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_scan_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "last_scan_status",
            sa.Enum("SUCCESS", "FAILURE", "PENDING", name="scanstatus"),
            nullable=True,
        ),
        sa.Column("last_scan_error_log", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_monitored_paths_id"), "monitored_paths", ["id"], unique=False)
    op.create_index(op.f("ix_monitored_paths_name"), "monitored_paths", ["name"], unique=False)

    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("color", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tags_id"), "tags", ["id"], unique=False)
    op.create_index(op.f("ix_tags_name"), "tags", ["name"], unique=True)

    op.create_table(
        "criteria",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("path_id", sa.Integer(), nullable=False),
        sa.Column(
            "criterion_type",
            sa.Enum(
                "MTIME",
                "ATIME",
                "CTIME",
                "SIZE",
                "NAME",
                "INAME",
                "TYPE",
                "PERM",
                "USER",
                "GROUP",
                name="criteriontype",
            ),
            nullable=False,
        ),
        sa.Column(
            "operator",
            sa.Enum(
                "GT", "LT", "EQ", "GTE", "LTE", "CONTAINS", "REGEX", "MATCHES", name="operator"
            ),
            nullable=False,
        ),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["path_id"],
            ["monitored_paths.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_criteria_id"), "criteria", ["id"], unique=False)
    
    op.create_table(
        "cold_storage_locations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("path"),
    )
    op.create_index(
        op.f("ix_cold_storage_locations_id"), "cold_storage_locations", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_cold_storage_locations_name"), "cold_storage_locations", ["name"], unique=True
    )

    op.create_table(
        "file_inventory",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("path_id", sa.Integer(), nullable=False),
        sa.Column("cold_storage_location_id", sa.Integer(), nullable=True),
        sa.Column("file_path", sa.String(), nullable=False),
        sa.Column("storage_type", sa.Enum("HOT", "COLD", name="storagetype"), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("file_mtime", sa.DateTime(timezone=True), nullable=False),
        sa.Column("file_atime", sa.DateTime(timezone=True), nullable=True),
        sa.Column("file_ctime", sa.DateTime(timezone=True), nullable=True),
        sa.Column("checksum", sa.String(), nullable=True),
        sa.Column("file_extension", sa.String(), nullable=True),
        sa.Column("mime_type", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "MOVED", "DELETED", "MISSING", name="filestatus"),
            nullable=True,
        ),
        sa.Column(
            "last_seen",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["path_id"],
            ["monitored_paths.id"],
        ),
        sa.ForeignKeyConstraint(
            ["cold_storage_location_id"],
            ["cold_storage_locations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sqlite_autoincrement=True,
    )
    op.create_index("idx_inventory_extension", "file_inventory", ["file_extension"], unique=False)
    op.create_index(
        "idx_inventory_path_storage_status",
        "file_inventory",
        ["path_id", "storage_type", "status"],
        unique=False,
    )
    op.create_index(
        "idx_inventory_storage_status_lastseen",
        "file_inventory",
        ["storage_type", "status", "last_seen"],
        unique=False,
    )
    op.create_index(
        op.f("ix_file_inventory_checksum"), "file_inventory", ["checksum"], unique=False
    )
    op.create_index(
        op.f("ix_file_inventory_file_atime"), "file_inventory", ["file_atime"], unique=False
    )
    op.create_index(
        op.f("ix_file_inventory_file_extension"), "file_inventory", ["file_extension"], unique=False
    )
    op.create_index(
        op.f("ix_file_inventory_file_mtime"), "file_inventory", ["file_mtime"], unique=False
    )
    op.create_index(
        op.f("ix_file_inventory_file_path"), "file_inventory", ["file_path"], unique=False
    )
    op.create_index(
        op.f("ix_file_inventory_file_size"), "file_inventory", ["file_size"], unique=False
    )
    op.create_index(op.f("ix_file_inventory_id"), "file_inventory", ["id"], unique=False)
    op.create_index(
        op.f("ix_file_inventory_last_seen"), "file_inventory", ["last_seen"], unique=False
    )
    op.create_index(op.f("ix_file_inventory_path_id"), "file_inventory", ["path_id"], unique=False)
    op.create_index(op.f("ix_file_inventory_status"), "file_inventory", ["status"], unique=False)
    op.create_index(
        op.f("ix_file_inventory_storage_type"), "file_inventory", ["storage_type"], unique=False
    )
    op.create_index(
        op.f("ix_file_inventory_cold_storage_location_id"),
        "file_inventory",
        ["cold_storage_location_id"],
        unique=False,
    )

    op.create_table(
        "file_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("path_id", sa.Integer(), nullable=True),
        sa.Column("cold_storage_location_id", sa.Integer(), nullable=True),
        sa.Column("original_path", sa.String(), nullable=False),
        sa.Column("cold_storage_path", sa.String(), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column(
            "moved_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "operation_type",
            sa.Enum("MOVE", "COPY", "SYMLINK", name="operationtype"),
            nullable=False,
        ),
        sa.Column("criteria_matched", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["path_id"],
            ["monitored_paths.id"],
        ),
        sa.ForeignKeyConstraint(
            ["cold_storage_location_id"],
            ["cold_storage_locations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_file_records_id"), "file_records", ["id"], unique=False)
    op.create_index(op.f("ix_file_records_moved_at"), "file_records", ["moved_at"], unique=False)
    op.create_index(
        op.f("ix_file_records_cold_storage_location_id"),
        "file_records",
        ["cold_storage_location_id"],
        unique=False,
    )

    op.create_table(
        "pinned_files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("path_id", sa.Integer(), nullable=True),
        sa.Column("file_path", sa.String(), nullable=False),
        sa.Column(
            "pinned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("pinned_by", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["path_id"],
            ["monitored_paths.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pinned_files_file_path"), "pinned_files", ["file_path"], unique=False)
    op.create_index(op.f("ix_pinned_files_id"), "pinned_files", ["id"], unique=False)

    op.create_table(
        "tag_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column(
            "criterion_type",
            sa.Enum(
                "EXTENSION",
                "PATH_PATTERN",
                "MIME_TYPE",
                "SIZE",
                "NAME_PATTERN",
                name="tagrulecriteriontype",
            ),
            nullable=False,
        ),
        sa.Column(
            "operator",
            sa.Enum(
                "GT", "LT", "EQ", "GTE", "LTE", "CONTAINS", "REGEX", "MATCHES", name="operator"
            ),
            nullable=False,
        ),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tag_rules_id"), "tag_rules", ["id"], unique=False)
    op.create_index(op.f("ix_tag_rules_tag_id"), "tag_rules", ["tag_id"], unique=False)

    op.create_table(
        "file_tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column(
            "tagged_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("tagged_by", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["file_inventory.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sqlite_autoincrement=True,
    )
    op.create_index("idx_file_tag_unique", "file_tags", ["file_id", "tag_id"], unique=True)
    op.create_index(op.f("ix_file_tags_file_id"), "file_tags", ["file_id"], unique=False)
    op.create_index(op.f("ix_file_tags_id"), "file_tags", ["id"], unique=False)
    op.create_index(op.f("ix_file_tags_tag_id"), "file_tags", ["tag_id"], unique=False)

    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "level", sa.Enum("INFO", "WARNING", "ERROR", name="notificationlevel"), nullable=False
        ),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notifications_created_at"), "notifications", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_notifications_id"), "notifications", ["id"], unique=False)
    op.create_index(op.f("ix_notifications_level"), "notifications", ["level"], unique=False)

    op.create_table(
        "notifiers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("type", sa.Enum("EMAIL", "GENERIC_WEBHOOK", name="notifiertype"), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "filter_level",
            sa.Enum("INFO", "WARNING", "ERROR", name="notificationlevel"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("smtp_host", sa.String(), nullable=True),
        sa.Column("smtp_port", sa.Integer(), nullable=True),
        sa.Column("smtp_user", sa.String(), nullable=True),
        sa.Column("smtp_password", sa.String(), nullable=True),
        sa.Column("smtp_sender", sa.String(), nullable=True),
        sa.Column("smtp_use_tls", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notifiers_id"), "notifiers", ["id"], unique=False)
    op.create_index(op.f("ix_notifiers_name"), "notifiers", ["name"], unique=False)

    op.create_table(
        "notification_dispatches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("notification_id", sa.Integer(), nullable=False),
        sa.Column("notifier_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.Enum("SUCCESS", "FAILED", name="dispatchstatus"), nullable=False),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["notification_id"],
            ["notifications.id"],
        ),
        sa.ForeignKeyConstraint(
            ["notifier_id"],
            ["notifiers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notification_dispatches_id"), "notification_dispatches", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_notification_dispatches_notification_id"),
        "notification_dispatches",
        ["notification_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_dispatches_notifier_id"),
        "notification_dispatches",
        ["notifier_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_dispatches_timestamp"),
        "notification_dispatches",
        ["timestamp"],
        unique=False,
    )
    
    op.create_table(
        "path_storage_location_association",
        sa.Column("path_id", sa.Integer(), nullable=False),
        sa.Column("storage_location_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["path_id"],
            ["monitored_paths.id"],
        ),
        sa.ForeignKeyConstraint(
            ["storage_location_id"],
            ["cold_storage_locations.id"],
        ),
        sa.PrimaryKeyConstraint("path_id", "storage_location_id"),
    )

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")

    op.drop_table("path_storage_location_association")

    op.drop_index(
        op.f("ix_notification_dispatches_timestamp"), table_name="notification_dispatches"
    )
    op.drop_index(
        op.f("ix_notification_dispatches_notifier_id"), table_name="notification_dispatches"
    )
    op.drop_index(
        op.f("ix_notification_dispatches_notification_id"), table_name="notification_dispatches"
    )
    op.drop_index(op.f("ix_notification_dispatches_id"), table_name="notification_dispatches")
    op.drop_table("notification_dispatches")

    op.drop_index(op.f("ix_notifiers_name"), table_name="notifiers")
    op.drop_index(op.f("ix_notifiers_id"), table_name="notifiers")
    op.drop_table("notifiers")

    op.drop_index(op.f("ix_notifications_level"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_created_at"), table_name="notifications")
    op.drop_table("notifications")

    op.drop_index(op.f("ix_file_tags_tag_id"), table_name="file_tags")
    op.drop_index(op.f("ix_file_tags_id"), table_name="file_tags")
    op.drop_index(op.f("ix_file_tags_file_id"), table_name="file_tags")
    op.drop_index("idx_file_tag_unique", table_name="file_tags")
    op.drop_table("file_tags")

    op.drop_index(op.f("ix_tag_rules_tag_id"), table_name="tag_rules")
    op.drop_index(op.f("ix_tag_rules_id"), table_name="tag_rules")
    op.drop_table("tag_rules")

    op.drop_index(op.f("ix_pinned_files_id"), table_name="pinned_files")
    op.drop_index(op.f("ix_pinned_files_file_path"), table_name="pinned_files")
    op.drop_table("pinned_files")

    op.drop_index(op.f("ix_file_records_cold_storage_location_id"), table_name="file_records")
    op.drop_index(op.f("ix_file_records_moved_at"), table_name="file_records")
    op.drop_index(op.f("ix_file_records_id"), table_name="file_records")
    op.drop_table("file_records")

    op.drop_index(op.f("ix_file_inventory_storage_type"), table_name="file_inventory")
    op.drop_index(op.f("ix_file_inventory_status"), table_name="file_inventory")
    op.drop_index(op.f("ix_file_inventory_path_id"), table_name="file_inventory")
    op.drop_index(op.f("ix_file_inventory_last_seen"), table_name="file_inventory")
    op.drop_index(op.f("ix__file_inventory_id"), table_name="file_inventory")
    op.drop_index(op.f("ix_file_inventory_file_size"), table_name="file_inventory")
    op.drop_index(op.f("ix_file_inventory_file_path"), table_name="file_inventory")
    op.drop_index(op.f("ix_file_inventory_file_mtime"), table_name="file_inventory")
    op.drop_index(op.f("ix_file_inventory_file_extension"), table_name="file_inventory")
    op.drop_index(op.f("ix_file_inventory_file_atime"), table_name="file_inventory")
    op.drop_index(op.f("ix_file_inventory_checksum"), table_name="file_inventory")
    op.drop_index("idx_inventory_storage_status_lastseen", table_name="file_inventory")
    op.drop_index("idx_inventory_path_storage_status", table_name="file_inventory")
    op.drop_index("idx_inventory_extension", table_name="file_inventory")
    op.drop_table("file_inventory")

    op.drop_index(op.f("ix_cold_storage_locations_name"), table_name="cold_storage_locations")
    op.drop_index(op.f("ix_cold_storage_locations_id"), table_name="cold_storage_locations")
    op.drop_table("cold_storage_locations")
    
    op.drop_index(op.f("ix_criteria_id"), table_name="criteria")
    op.drop_table("criteria")

    op.drop_index(op.f("ix_tags_name"), table_name="tags")
    op.drop_index(op.f("ix_tags_id"), table_name="tags")
    op.drop_table("tags")

    op.drop_index(op.f("ix_monitored_paths_name"), table_name="monitored_paths")
    op.drop_index(op.f("ix_monitored_paths_id"), table_name="monitored_paths")
    op.drop_table("monitored_paths")
    # ### end Alembic commands ###
