"""add_smtp_settings_to_instance_metadata

Revision ID: be6a79404001
Revises: f1a2b3c4d5e6
Create Date: 2026-06-03 14:54:54.822526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be6a79404001'
down_revision: Union[str, None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = set(inspector.get_table_names())
    if "instance_metadata" not in tables:
        return

    columns = {column["name"] for column in inspector.get_columns("instance_metadata")}

    with op.batch_alter_table("instance_metadata") as batch_op:
        if "smtp_host" not in columns:
            batch_op.add_column(sa.Column("smtp_host", sa.String(), nullable=True))
        if "smtp_port" not in columns:
            batch_op.add_column(sa.Column("smtp_port", sa.Integer(), nullable=True, server_default='587'))
        if "smtp_user" not in columns:
            batch_op.add_column(sa.Column("smtp_user", sa.String(), nullable=True))
        if "smtp_password" not in columns:
            batch_op.add_column(sa.Column("smtp_password", sa.String(), nullable=True))
        if "smtp_sender" not in columns:
            batch_op.add_column(sa.Column("smtp_sender", sa.String(), nullable=True))
        if "smtp_use_tls" not in columns:
            batch_op.add_column(sa.Column("smtp_use_tls", sa.Boolean(), nullable=True, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = set(inspector.get_table_names())
    if "instance_metadata" not in tables:
        return

    columns = {column["name"] for column in inspector.get_columns("instance_metadata")}

    with op.batch_alter_table("instance_metadata") as batch_op:
        if "smtp_use_tls" in columns:
            batch_op.drop_column("smtp_use_tls")
        if "smtp_sender" in columns:
            batch_op.drop_column("smtp_sender")
        if "smtp_password" in columns:
            batch_op.drop_column("smtp_password")
        if "smtp_user" in columns:
            batch_op.drop_column("smtp_user")
        if "smtp_port" in columns:
            batch_op.drop_column("smtp_port")
        if "smtp_host" in columns:
            batch_op.drop_column("smtp_host")
    # ### end Alembic commands ###
