"""Add external notification system tables

Revision ID: e58a2557bb63
Revises: 5f96d3126e3a
Create Date: 2026-01-06 19:32:17.955128

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e58a2557bb63"
down_revision: Union[str, None] = "5f96d3126e3a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("notifications",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("level", sa.Enum("INFO", "WARNING", "ERROR", name="notificationlevel"), nullable=False),
    sa.Column("message", sa.Text(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_notifications_created_at"), "notifications", ["created_at"], unique=False)
    op.create_index(op.f("ix_notifications_id"), "notifications", ["id"], unique=False)
    op.create_index(op.f("ix_notifications_level"), "notifications", ["level"], unique=False)
    op.create_table("notifiers",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("name", sa.String(), nullable=False),
    sa.Column("type", sa.Enum("EMAIL", "GENERIC_WEBHOOK", name="notifiertype"), nullable=False),
    sa.Column("address", sa.String(), nullable=False),
    sa.Column("enabled", sa.Boolean(), nullable=False),
    sa.Column("filter_level", sa.Enum("INFO", "WARNING", "ERROR", name="notificationlevel"), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_notifiers_id"), "notifiers", ["id"], unique=False)
    op.create_index(op.f("ix_notifiers_name"), "notifiers", ["name"], unique=False)
    op.create_table("notification_dispatches",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("notification_id", sa.Integer(), nullable=False),
    sa.Column("notifier_id", sa.Integer(), nullable=False),
    sa.Column("status", sa.Enum("SUCCESS", "FAILED", name="dispatchstatus"), nullable=False),
    sa.Column("details", sa.Text(), nullable=True),
    sa.Column("timestamp", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
    sa.ForeignKeyConstraint(["notification_id"], ["notifications.id"], ),
    sa.ForeignKeyConstraint(["notifier_id"], ["notifiers.id"], ),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_notification_dispatches_id"), "notification_dispatches", ["id"], unique=False)
    op.create_index(op.f("ix_notification_dispatches_notification_id"), "notification_dispatches", ["notification_id"], unique=False)
    op.create_index(op.f("ix_notification_dispatches_notifier_id"), "notification_dispatches", ["notifier_id"], unique=False)
    op.create_index(op.f("ix_notification_dispatches_timestamp"), "notification_dispatches", ["timestamp"], unique=False)
    op.drop_index(op.f("idx_inventory_checksum"), table_name="file_inventory")
    op.drop_index(op.f("idx_file_tags_file_id"), table_name="file_tags")
    op.drop_index(op.f("idx_file_tags_tag_id"), table_name="file_tags")
    op.drop_index(op.f("idx_tag_rules_enabled"), table_name="tag_rules")
    op.drop_index(op.f("idx_tag_rules_priority"), table_name="tag_rules")
    op.drop_index(op.f("idx_tag_rules_tag_id"), table_name="tag_rules")
    op.drop_index(op.f("idx_tags_name"), table_name="tags")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("idx_tags_name"), "tags", ["name"], unique=False)
    op.create_index(op.f("idx_tag_rules_tag_id"), "tag_rules", ["tag_id"], unique=False)
    op.create_index(op.f("idx_tag_rules_priority"), "tag_rules", ["priority"], unique=False)
    op.create_index(op.f("idx_tag_rules_enabled"), "tag_rules", ["enabled"], unique=False)
    op.create_index(op.f("idx_file_tags_tag_id"), "file_tags", ["tag_id"], unique=False)
    op.create_index(op.f("idx_file_tags_file_id"), "file_tags", ["file_id"], unique=False)
    op.create_index(op.f("idx_inventory_checksum"), "file_inventory", ["checksum"], unique=False)
    op.drop_index(op.f("ix_notification_dispatches_timestamp"), table_name="notification_dispatches")
    op.drop_index(op.f("ix_notification_dispatches_notifier_id"), table_name="notification_dispatches")
    op.drop_index(op.f("ix_notification_dispatches_notification_id"), table_name="notification_dispatches")
    op.drop_index(op.f("ix_notification_dispatches_id"), table_name="notification_dispatches")
    op.drop_table("notification_dispatches")
    op.drop_index(op.f("ix_notifiers_name"), table_name="notifiers")
    op.drop_index(op.f("ix_notifiers_id"), table_name="notifiers")
    op.drop_table("notifiers")
    op.drop_index(op.f("ix_notifications_level"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_created_at"), table_name="notifications")
    op.drop_table("notifications")
    # ### end Alembic commands ###
