"""Add event-based notification subscriptions and disk space thresholds

Revision ID: ee1a21b76bf2
Revises: 1eab9db4e223
Create Date: 2026-01-17 21:42:40.567878

"""

import json
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ee1a21b76bf2"
down_revision: Union[str, None] = "1eab9db4e223"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Migrate from level-based to event-based notification subscriptions."""

    # 1. Add disk space threshold columns to cold_storage_locations with defaults
    op.add_column(
        "cold_storage_locations",
        sa.Column("caution_threshold_percent", sa.Integer(), nullable=False, server_default="20"),
    )
    op.add_column(
        "cold_storage_locations",
        sa.Column("critical_threshold_percent", sa.Integer(), nullable=False, server_default="10"),
    )

    # 2. Add subscribed_events column (nullable initially for data migration)
    with op.batch_alter_table("notifiers") as batch_op:
        batch_op.add_column(sa.Column("subscribed_events", sa.JSON(), nullable=True))

    # 3. Migrate existing filter_level values to subscribed_events
    conn = op.get_bind()
    notifiers = conn.execute(sa.text("SELECT id, filter_level FROM notifiers")).fetchall()

    # Define mapping from filter_level to event subscriptions
    event_mapping = {
        "error": ["SCAN_ERROR", "DISK_SPACE_CRITICAL"],
        "warning": ["SCAN_ERROR", "DISK_SPACE_CRITICAL", "DISK_SPACE_CAUTION"],
        "info": [
            "SCAN_COMPLETED",
            "SCAN_ERROR",
            "PATH_CREATED",
            "PATH_UPDATED",
            "PATH_DELETED",
            "DISK_SPACE_CAUTION",
            "DISK_SPACE_CRITICAL",
        ],
    }

    # Migrate each notifier
    for notifier_id, filter_level in notifiers:
        events = event_mapping.get((filter_level or "info").lower(), event_mapping.get("info", []))
        conn.execute(
            sa.text("UPDATE notifiers SET subscribed_events = :events WHERE id = :id"),
            {"events": json.dumps(events), "id": notifier_id},
        )

    # 4. Make subscribed_events non-nullable with default empty array
    with op.batch_alter_table("notifiers") as batch_op:
        batch_op.alter_column("subscribed_events", nullable=False, server_default="[]")

    # 5. Drop filter_level column
    with op.batch_alter_table("notifiers") as batch_op:
        batch_op.drop_column("filter_level")

    # 6. Clean up indexes (SQLite doesn't need explicit drops, but keeping for compatibility)
    # These are autogenerated cleanup operations - safe to skip for SQLite


def downgrade() -> None:
    """Reverse migration: event-based back to level-based notifications."""

    # 1. Add filter_level column back (nullable initially for data migration)
    with op.batch_alter_table("notifiers") as batch_op:
        batch_op.add_column(sa.Column("filter_level", sa.VARCHAR(length=7), nullable=True))

    # 2. Reverse-migrate subscribed_events to filter_level
    conn = op.get_bind()
    notifiers = conn.execute(sa.text("SELECT id, subscribed_events FROM notifiers")).fetchall()

    for notifier_id, events_json in notifiers:
        events = []
        if isinstance(events_json, list):
            events = events_json
        elif events_json:
            try:
                events = json.loads(events_json)
            except (json.JSONDecodeError, TypeError):
                events = []

        # Determine filter_level based on subscribed events
        # If subscribed to info-level events → INFO
        # If subscribed to warning-level events → WARNING
        # Otherwise → ERROR
        if "SCAN_COMPLETED" in events or "PATH_CREATED" in events:
            level = "info"
        elif "DISK_SPACE_CAUTION" in events:
            level = "warning"
        else:
            level = "error"

        conn.execute(
            sa.text("UPDATE notifiers SET filter_level = :level WHERE id = :id"),
            {"level": level, "id": notifier_id},
        )

    # 3. Make filter_level non-nullable
    with op.batch_alter_table("notifiers") as batch_op:
        batch_op.alter_column("filter_level", nullable=False, server_default="info")

    # 4. Drop subscribed_events column
    with op.batch_alter_table("notifiers") as batch_op:
        batch_op.drop_column("subscribed_events")

    # 5. Drop threshold columns from cold_storage_locations
    op.drop_column("cold_storage_locations", "critical_threshold_percent")
    op.drop_column("cold_storage_locations", "caution_threshold_percent")
