"""Add SMTP settings to notifiers

Revision ID: f263f88663c0
Revises: e58a2557bb63
Create Date: 2026-01-06 19:44:30.637941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f263f88663c0'
down_revision: Union[str, None] = 'e58a2557bb63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_inventory_checksum'), table_name='file_inventory')
    op.drop_index(op.f('idx_file_tags_file_id'), table_name='file_tags')
    op.drop_index(op.f('idx_file_tags_tag_id'), table_name='file_tags')
    op.add_column('notifiers', sa.Column('smtp_host', sa.String(), nullable=True))
    op.add_column('notifiers', sa.Column('smtp_port', sa.Integer(), nullable=True))
    op.add_column('notifiers', sa.Column('smtp_user', sa.String(), nullable=True))
    op.add_column('notifiers', sa.Column('smtp_password', sa.String(), nullable=True))
    op.add_column('notifiers', sa.Column('smtp_sender', sa.String(), nullable=True))
    op.add_column('notifiers', sa.Column('smtp_use_tls', sa.Boolean(), nullable=True))
    op.drop_index(op.f('idx_tag_rules_enabled'), table_name='tag_rules')
    op.drop_index(op.f('idx_tag_rules_priority'), table_name='tag_rules')
    op.drop_index(op.f('idx_tag_rules_tag_id'), table_name='tag_rules')
    op.drop_index(op.f('idx_tags_name'), table_name='tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_tags_name'), 'tags', ['name'], unique=False)
    op.create_index(op.f('idx_tag_rules_tag_id'), 'tag_rules', ['tag_id'], unique=False)
    op.create_index(op.f('idx_tag_rules_priority'), 'tag_rules', ['priority'], unique=False)
    op.create_index(op.f('idx_tag_rules_enabled'), 'tag_rules', ['enabled'], unique=False)
    op.drop_column('notifiers', 'smtp_use_tls')
    op.drop_column('notifiers', 'smtp_sender')
    op.drop_column('notifiers', 'smtp_password')
    op.drop_column('notifiers', 'smtp_user')
    op.drop_column('notifiers', 'smtp_port')
    op.drop_column('notifiers', 'smtp_host')
    op.create_index(op.f('idx_file_tags_tag_id'), 'file_tags', ['tag_id'], unique=False)
    op.create_index(op.f('idx_file_tags_file_id'), 'file_tags', ['file_id'], unique=False)
    op.create_index(op.f('idx_inventory_checksum'), 'file_inventory', ['checksum'], unique=False)
    # ### end Alembic commands ###
