"""Fix remote_connections schema

Revision ID: f9251147202f
Revises: 2c525e893192
Create Date: 2026-01-24 20:51:36.560672

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f9251147202f"
down_revision: Union[str, None] = "2c525e893192"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("file_inventory", "status",
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum("ACTIVE", "MOVED", "DELETED", "MISSING", "MIGRATING", name="filestatus"),
               existing_nullable=True)
    op.drop_index(op.f("idx_file_inventory_cold_storage_location_id"), table_name="file_inventory")
    op.drop_index(op.f("idx_inventory_checksum"), table_name="file_inventory")
    op.drop_index(op.f("idx_file_records_cold_storage_location_id"), table_name="file_records")
    op.drop_index(op.f("idx_file_tags_file_id"), table_name="file_tags")
    op.drop_index(op.f("idx_file_tags_tag_id"), table_name="file_tags")
    op.alter_column("file_transaction_history", "transaction_type",
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum("FREEZE", "THAW", "MOVE_COLD", "DELETE", "COPY", "RESTORE", "CLEANUP", "REMOTE_MIGRATE", "REMOTE_RECEIVE", name="transactiontype"),
               existing_nullable=False)
    op.alter_column("notifiers", "id",
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column("notifiers", "subscribed_events",
               existing_type=sqlite.JSON(),
               nullable=False)

    # Drop old remote_connections columns and add new ones
    op.drop_index(op.f("idx_remote_connections_remote_instance_uuid"), table_name="remote_connections")
    op.drop_column("remote_connections", "remote_instance_uuid")
    op.drop_column("remote_connections", "shared_secret") # Manually added

    op.add_column("remote_connections", sa.Column("remote_fingerprint", sa.String(), nullable=True)) # Manually added
    op.add_column("remote_connections", sa.Column("remote_ed25519_public_key", sa.Text(), nullable=True)) # Manually added
    op.add_column("remote_connections", sa.Column("remote_x25519_public_key", sa.Text(), nullable=True)) # Manually added
    op.add_column("remote_connections", sa.Column("trust_status", sa.Enum("PENDING", "TRUSTED", "REJECTED", name="truststatus"), nullable=False, server_default=sa.text("'PENDING'"))) # Manually added
    op.create_index(op.f("ix_remote_connections_remote_fingerprint"), "remote_connections", ["remote_fingerprint"], unique=True) # Manually added

    op.drop_index(op.f("idx_tag_rules_enabled"), table_name="tag_rules")
    op.drop_index(op.f("idx_tag_rules_priority"), table_name="tag_rules")
    op.drop_index(op.f("idx_tag_rules_tag_id"), table_name="tag_rules")
    op.drop_index(op.f("idx_tags_name"), table_name="tags")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("idx_tags_name"), "tags", ["name"], unique=False)
    op.create_index(op.f("idx_tag_rules_tag_id"), "tag_rules", ["tag_id"], unique=False)
    op.create_index(op.f("idx_tag_rules_priority"), "tag_rules", ["priority"], unique=False)
    op.create_index(op.f("idx_tag_rules_enabled"), "tag_rules", ["enabled"], unique=False)

    # Revert remote_connections changes
    op.drop_index(op.f("ix_remote_connections_remote_fingerprint"), table_name="remote_connections") # Manually added
    op.drop_column("remote_connections", "trust_status") # Manually added
    op.drop_column("remote_connections", "remote_x25519_public_key") # Manually added
    op.drop_column("remote_connections", "remote_ed25519_public_key") # Manually added
    op.drop_column("remote_connections", "remote_fingerprint") # Manually added

    op.add_column("remote_connections", sa.Column("shared_secret", sa.VARCHAR(), nullable=False)) # Manually added, assuming it was nullable=False before
    op.add_column("remote_connections", sa.Column("remote_instance_uuid", sa.TEXT(), nullable=True))
    op.create_index(op.f("idx_remote_connections_remote_instance_uuid"), "remote_connections", ["remote_instance_uuid"], unique=1)

    op.alter_column("notifiers", "subscribed_events",
               existing_type=sqlite.JSON(),
               nullable=True)
    op.alter_column("notifiers", "id",
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column("file_transaction_history", "transaction_type",
               existing_type=sa.Enum("FREEZE", "THAW", "MOVE_COLD", "DELETE", "COPY", "RESTORE", "CLEANUP", "REMOTE_MIGRATE", "REMOTE_RECEIVE", name="transactiontype"),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
    op.create_index(op.f("idx_file_tags_tag_id"), "file_tags", ["tag_id"], unique=False)
    op.create_index(op.f("idx_file_tags_file_id"), "file_tags", ["file_id"], unique=False)
    op.create_index(op.f("idx_file_records_cold_storage_location_id"), "file_records", ["cold_storage_location_id"], unique=False)
    op.create_index(op.f("idx_inventory_checksum"), "file_inventory", ["checksum"], unique=False)
    op.create_index(op.f("idx_file_inventory_cold_storage_location_id"), "file_inventory", ["cold_storage_location_id"], unique=False)
    op.alter_column("file_inventory", "status",
               existing_type=sa.Enum("ACTIVE", "MOVED", "DELETED", "MISSING", "MIGRATING", name="filestatus"),
               type_=sa.VARCHAR(length=7),
               existing_nullable=True)
    # ### end Alembic commands ###
